// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://emkcaalgfutbukindxvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVta2NhYWxnZnV0YnVraW5keHZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyMDU2NjIsImV4cCI6MjA4Nzc4MTY2Mn0.zV462shaSHLNm8jIN57aPmvL3pEoAHff9fCCxdKTo5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});